### ISSUE TITLE
add tldr entry

### ISSUE THREAD

**Issue by FLX-0x00** [evait-security/wami#5]
❯ tldr wami
Warning: The cache hasn't been updated for 42 days.
You should probably run `tldr --update` soon.
Warning: Page `wami` not found in cache.
Try updating with `tldr --update`, or submit a pull request to:
https://github.com/tldr-pages/tldr

**Comment by NxtTAB** [comment]
https://github.com/NxtTAB/tldr-wami
Whating on PR of [tldr-pages](https://github.com/tldr-pages/tldr)
